version: "2.2"
services:
  io-onboarding-pa:
    container_name: io-onboarding-pa
    image: teamdigitale/io-onboarding-pa
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    restart: always
