version: "3.2"
services:
  io-onboarding-pa:
    image: teamdigitale/io-onboarding-pa
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:80"
    networks:
      - io-onboarding

networks:
  io-onboarding:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
